---
title: "San Diego's Ocean Water Monitoring Program"
author: "Group 3"
date: "11/14/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE,message=FALSE}
# R Libraries
library(astsa)
library(RCurl)
library(psych)
library(dplyr)
library(RSQLite)
library(naniar)
library(ggplot2)
```

```{r, warning=FALSE,message=FALSE}
# Datasets (3 CSV files)
csv1 <- getURL("http://seshat.datasd.org/pud/omp/water_quality_2011_2019_datasd.csv")
csv2 <- getURL("http://seshat.datasd.org/pud/omp/water_quality_2000_2010_datasd.csv")
csv3 <- getURL("http://seshat.datasd.org/pud/omp/water_quality_1990_1999_datasd.csv")
stationsCSV <- getURL("http://seshat.datasd.org/pud/omp/reference_stations_water_quality.csv")
csv1dl <- read.csv( text = csv1 )
csv2dl <- read.csv( text = csv2 )
csv3dl <- read.csv( text = csv3 )
stationsdl <- read.csv( text = stationsCSV )
```

```{r, warning=FALSE,message=FALSE}
# Bind data from 3 CSV files into one dataframe
csvs <- rbind(csv1dl, csv2dl, csv3dl)
# Bind stations data into dataframe
stations <- rbind(stationsdl)
```

```{r, warning=FALSE,message=FALSE}
conn <- dbConnect(RSQLite::SQLite(), "ADS506.db") # to create a SQL database in memory
copy_to(conn,
        csvs, # load csvs dataframe into SQL
        overwrite = TRUE) # if exists, overwrite
copy_to(conn,
        stations, # load stations dataframe into SQL
        overwrite = TRUE) # if exists, overwrite
```

```{r, warning=FALSE,message=FALSE}
# combine information from both dataframes into one
df <- dbGetQuery(conn, sql("
SELECT csvs.*, s.lat, s.long 
FROM csvs 
left join stations as s 
on csvs.station = s.[ï..station]
"))
# disconnect from database
dbDisconnect(conn)
# clean up data that is no longer needed
rm(conn, csvs, csv1dl, csv2dl , csv3dl, csv1, csv2, csv3, stations, stationsdl, stationsCSV)
```

```{r}
# Plot missing data
vis_miss((df), warn_large_data = FALSE)
````

```{r}
str(df)
```

```{r, warning=FALSE,message=FALSE}
#describe(df$depth_m)
ggplot(df, aes(x=df$depth_m)) +
  geom_boxplot(color="darkblue", fill="lightblue") +
  geom_density()
```

```{r, warning=FALSE,message=FALSE}
df %>% group_by(project) %>% summarise(n=n()) %>% mutate(freq = n / sum(n))
```


# abby's input

```{r}
df <- read.csv(file = 'C:/Users/abby0/OneDrive/Desktop/MSADS/ADS-506 Applied Time Series Analysis/Final project/data_final.csv')
```

```{r}
df.val <- df[c('value')]
df.ts <- ts(df.test, frequency=12, start=c(1991))
df.ts
```

```{r}
plot(df.ts)
```

```{r}
# ACF shows significant autocorrelation. observations are not independent.
par(mfrow = c(2, 1))
acf(df.ts)
pacf(df.ts)
```

```{r}
diff_df.ts <- diff(df.ts)
plot(diff_df.ts)
```

```{r}
# ACF shows AR(1). PACF MA(2)?
par(mfrow = c(2, 1))
acf(diff_df.ts)
pacf(diff_df.ts)
```

```{r}
sarima.for(diff_df.ts,6,1,0,2)
```

```{r}
fit <- sarima(diff_df.ts, 1,0,2)
```
